@Library('Shared') _ // https://github.com/HasanAshab/Jenkins_SharedLib
pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
        disableConcurrentBuilds()
        durabilityHint('PERFORMANCE_OPTIMIZED')
        preserveStashes(buildCount: 5)
    }

    tools {
        nodejs 'node:18'
    }

    parameters {
        string(name: 'GIT_BRANCH', defaultValue: '', description: 'Branch name of the commit')
        string(name: 'SHORT_SHA', defaultValue: '', description: 'Short SHA of the commit')
    }

    stages {
        stage('Validate Params') {
            steps {
                script {
                    if (!params.GIT_BRANCH?.trim()) {
                        error "Parameter GIT_BRANCH is required but not provided!"
                    }
                    if (!params.SHORT_SHA?.trim()) {
                        error "Parameter SHORT_SHA is required but not provided!"
                    }
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') { 
                    sh 'npm ci'
                }
            }
        }

        stage('CI') {
            parallel {
                stage('Run Lint') {
                    steps {
                        dir('frontend') {
                            sh 'npm run lint'
                        }
                    }
                }

                stage('Run Tests') {
                    steps {
                        dir('frontend') {
                            sh 'npm test'
                        }
                    }
                }
            } 
        }
  
        stage('Docker') {
            steps {
                script {
                    docker_build_scan_push(
                        CredId: 'docker',
                        Registry: 'docker.io',
                        ImageBase: 'wanderlust',
                        ImageSuffix: 'frontend',
                        Tags: [params.SHORT_SHA, 'latest'],
                        Push: env.GIT_BRANCH == 'main',
                    )
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success { echo '✅ Pipeline succeeded!' }
        failure { echo '❌ Pipeline failed!' }
    }
}
